#ifndef GUI_NAMESPACE_H
#define GUI_NAMESPACE_H

#ifndef GUI_NAMESPACE_BEGIN
#   define GUI_NAMESPACE_BEGIN namespace gui {
#endif //GUI_NAMESPACE_BEGIN

#ifndef GUI_NAMESPACE_END
#   define GUI_NAMESPACE_END }
#endif //GUI_NAMESPACE_END

#endif //GUI_NAMESPACE_H